config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin/neil/secret', as: 'rails_admin'
  devise_for :users
  
  resources :categories
  
  resources :orders
  
  resources :line_items do
     resources :orders
   end
  resources :carts
  
  resources :products do
  get :who_bought, on: :member
  end
  
  resources :greetings

  get 'pages/about'

  get 'pages/contact'

  get 'pages/services'

  get 'store/index'

  root 'store#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
     has_attached_file   :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "images.jpg"
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    has_many :line_items
    has_many :orders, through: :line_items
    belongs_to :categories
    before_destroy :ensure_not_referenced_by_any_line_item
  
    
    private
    def ensure_not_referenced_by_any_line_item
        if line_items.empty?
        return true
    else
        errors.add(:base, 'Line Items present')
        return false
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image, :quantity)
    end
    
    def who_bought
      @product = Product.find(params[:id])
      respond_to do |format|
      format.atom
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<div class="centre">
  <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4">
          <div class="thumbnail">
            <%= link_to image_tag(product.image.url), product %>
              <div class="caption">
              <h3><%= product.title %><h3>
                <p><%= number_to_currency(product.price, unit: "€",) %></p>
                <%= link_to 'Discover More', product, class: "btn btn-link" %>
                <p><%= link_to 'Your Cart', line_items_path(product_id: product)%></p>
              </div>
          </div>
        </div>
        <% end %>
</div>
</div>
<br>

<%= link_to 'New Product', new_product_path, class: "btn btn-link" %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-md-6">
      <div class ="thumbnail">
        <%= image_tag @product.image.url(:medium) %>
        </div>
     </div>
    <div class="col-md-6">
      <h3><%= @product.title %></h3>
      <p>  <%= @product.description %></p>
      <p>  <%= number_to_currency(@product.price, unit: "€") %></p>
  </div>
  </div>
  

 <p><%= link_to 'Add to Cart', line_items_path, class: "btn btn-primary"%></p>
<%= link_to 'Back', products_path, class: "btn btn-link" %>