config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin/neil/secret', as: 'rails_admin'
  devise_for :users
  
  resources :categories
  
  resources :orders
  
  resources :line_items do
     resources :orders
   end
  resources :carts
  
  resources :products do
  get :who_bought, on: :member
  end
  
  resources :greetings

  get 'pages/about'

  get 'pages/contact'

  get 'pages/services'

  get 'store/index'

  root 'store#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity = 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
  def total_items
    line_items.sum(:quantity)
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :products
end

app/models/greeting.rb
class Greeting < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
    belongs_to :product
    belongs_to :order
    belongs_to :cart
    
    def total_price
    product.price
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    belongs_to :users
    
    def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
         item.cart_id = nil
         line_items << item
        end
    end
      validates :name, :email, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
     has_attached_file   :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "images.jpg"
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    has_many :line_items
    has_many :orders, through: :line_items
    belongs_to :categories
    before_destroy :ensure_not_referenced_by_any_line_item
  
    
    private
    def ensure_not_referenced_by_any_line_item
        if line_items.empty?
        return true
    else
        errors.add(:base, 'Line Items present')
        return false
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
      begin
        @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        logger.error "Attempt to access invalid cart #{params[:id]}"
         redirect_to store_url, notice: 'Invalid cart'
      else
        respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
      end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:quantity, :product_id, :line_items, :total_price, :total_items)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
   @orders = Order.all
  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @orders }
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
  @cart = current_cart
   if @cart.line_items.empty?
     redirect_to store_index_path, notice: "Your cart is empty"
     return
   end
  
  @order = Order.new
  @order.add_line_items_from_cart(current_cart)
  respond_to do |format|
    format.html # new.html.erb
    format.json { render json: @order }
  end
  end
  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])
    @order.add_line_items_from_cart(current_cart)
    @order.user_id = current_user.id
    
    respond_to do |format|
      if @order.save
       # Cart.destroy(session[:cart_id])
       # session[:cart_id] = nil
        # Add in thank you page here (below)
        format.html { redirect_to store_index_path, notice: 'Order was successfully placed.' }
        format.json { render :show, status: :created, location: @order }
      else
        @cart = current_cart
        format.html { render action "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :email, :total_price)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def services
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    if params[:set_locale]
    redirect_to store_index_path(locale: params[:set_locale])
  else
    @products = Product.order(:title)
    @cart = current_cart
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
     def hidden_div_if(condition, attributes = {}, &block)
         if condition
         attributes["style"] = "display: none"
         end
        content_tag("div", attributes, &block)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse">
 <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-footer">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Webconcierge</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
        <li><a href="/pages/services">Services</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

         <li><%= link_to "Your Cart", line_items_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-inverse">
 <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Webconcierge</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %>></li>
        <li><%= link_to "Services", pages_services_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Sign Out",  destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Edit Profile",  edit_user_registration_path %></li>
        <% else %>
        <li><%= link_to "Sign Up",  new_user_registration_path %></li>
        <li><%= link_to "Log In",  new_user_session_path %></li>
      <% end %>

         <li><%= link_to "Your Cart", line_items_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webconcierge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/header' %>

<div class="container">
        
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
              
            <% end %>
          <% end %>  
        
  
  <%= yield %>




<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>